// Datos de ejemplo (ampliados)
export const quotes = [
    {
      id: 1,
      text: "En el momento en que uno se propone definitivamente a sí mismo, entonces la providencia también se pone en movimiento.",
      book: "El Alquimista",
      author: "Paulo Coelho",
      user: "María García",
      likes: 142,
    },
    {
      id: 2,
      text: "No es más que un zorro semejante a cien mil otros. Pero yo le hice mi amigo y ahora es único en el mundo.",
      book: "El Principito",
      author: "Antoine de Saint-Exupéry",
      user: "Juan Pérez",
      likes: 137,
    },
    {
      id: 3,
      text: "La verdadera sabiduría está en reconocer la propia ignorancia.",
      book: "Sócrates",
      author: "Platón",
      user: "Ana Martínez",
      likes: 128,
    },
    {
      id: 4,
      text: "El único lugar donde tus sueños son imposibles es en tu propia mente.",
      book: "El Alquimista",
      author: "Paulo Coelho",
      user: "Pedro López",
      likes: 115,
    },
    {
      id: 5,
      text: "Lo esencial es invisible a los ojos.",
      book: "El Principito",
      author: "Antoine de Saint-Exupéry",
      user: "Laura Rodríguez",
      likes: 110,
    },
    {
      id: 6,
      text: "La vida es lo que te sucede mientras estás ocupado haciendo otros planes.",
      book: "John Lennon",
      author: "John Lennon",
      user: "Carlos Gómez",
      likes: 105,
    },
    {
      id: 7,
      text: "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.",
      book: "Winston Churchill",
      author: "Winston Churchill",
      user: "Sofia Hernández",
      likes: 98,
    },
    {
      id: 8,
      text: "La única manera de hacer un gran trabajo es amar lo que haces.",
      book: "Steve Jobs",
      author: "Steve Jobs",
      user: "David Moreno",
      likes: 92,
    },
    {
      id: 9,
      text: "La imaginación es más importante que el conocimiento.",
      book: "Albert Einstein",
      author: "Albert Einstein",
      user: "Isabel Sánchez",
      likes: 87,
    },
    {
      id: 10,
      text: "El futuro pertenece a aquellos que creen en la belleza de sus sueños.",
      book: "Eleanor Roosevelt",
      author: "Eleanor Roosevelt",
      user: "Javier Ruiz",
      likes: 80,
    },
    {
      id: 11,
      text: "La perseverancia es el camino hacia el éxito.",
      book: "Proverbio Chino",
      author: "Proverbio Chino",
      user: "Andrea Álvarez",
      likes: 75,
    },
    {
      id: 12,
      text: "La felicidad no es la ausencia de problemas, sino la capacidad de superarlos.",
      book: "Steve Maraboli",
      author: "Steve Maraboli",
      user: "Miguel Santos",
      likes: 70,
    },
    {
      id: 13,
      text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
      book: "Albert Schweitzer",
      author: "Albert Schweitzer",
      user: "Elena López",
      likes: 65,
    },
    {
      id: 14,
      text: "La mejor manera de predecir el futuro es creándolo.",
      book: "Peter Drucker",
      author: "Peter Drucker",
      user: "Pablo Martín",
      likes: 60,
    },
    {
      id: 15,
      text: "El conocimiento es poder.",
      book: "Francis Bacon",
      author: "Francis Bacon",
      user: "Lucía García",
      likes: 55,
    },
  ]
  